# main.yml
---
  - name: Upload application file
    copy:
      src: ../files/index.php
      dest: "{{ path_to_app }}"
      mode: 0755
  - name: Create simple info page
    copy:
      dest: "{{ path_to_app }}/info.php"
      content: '<h1> you hostname is: {{ansible_hostname}}</h1>'
  - name: See content folder
    command: "ls -al {{ path_to_app }}"
    register: folder_content
  - name: Debug folder
    debug:
      msg: "{{folder_content}}"
  - name: Configure php.ini file
    lineinfile:
      path: /etc/php.ini
      regexp: ^short_open_tag
      line: 'short_open_tag=On'
    notify: Restart apache